#!/bin/bash
php="C:\wamp\bin\php\php5.3.9\php.exe"
errors=0
files=0
ignored=0
for i in $(git diff-index --name-only --cached HEAD)
	do
		files=$((files+1))
		result=$(echo $i | perl -ne "/(Thumbs\.db|\.DS_Store|\._.*)$/ && print")
		if [ -n "$result" ]; then #string wasn't empty - so we don't want this file.
		#some files shouldn't be commited
			errors=$((errors+1))
			echo "$i is a gunk file. Add it to .gitignore"
			continue;
		fi
		
		#break up the file for the extention
		filename=$(basename $i)
		extension=${filename##*.}
		filename=${filename%.*}
		case "$extension" in
			php) 
				#run lint
				output=$($php -d display_errors=1 -l $i 2>/dev/null)
				if [ "$output" != "No syntax errors detected in $i" ]; then
					echo $output
					errors=$((errors+1))
				fi
			;;
			*)
				#ignore file
				ignored=$((ignored+1))
		esac
	done
echo ""
echo "Files checked:" $files "| Errors found:" $errors "| Files ignored:" $ignored
if [ $errors = 0 ]; then
	exit 0
else
	exit 1
fi
